import json
from playwright.sync_api import sync_playwright, expect
from userscript_fixture import choose_option, ROOT, browser_options, userscript_source


with sync_playwright() as p:
    browser = p.chromium.launch(**browser_options(), headless=True, args=['--mute-audio'])
    for width in [1440, 390]:
        first_context = browser.new_context(viewport={'width':width, 'height':844})
        first_context.route('https://soundcloud.com/**', lambda route: route.fulfill(path=str(ROOT/'tests/fixtures/inline-fixture.html'), content_type='text/html'))
        first_context.add_init_script(userscript_source(first_run=True))
        first_page = first_context.new_page()
        first_page.goto('https://soundcloud.com/test-artist/first-track')
        expect(first_page.locator('.settings[data-choosing-style]')).to_be_visible()
        expect(first_page.locator('#control-style').locator('..').locator('.tempo-choice-trigger')).to_be_focused()
        expect(first_page.locator('#control-style option')).to_have_count(3)
        expect(first_page.get_by_label('Show semitone adjustment in player', exact=True)).to_be_visible()
        first_page.locator('#show-key').uncheck()
        choose_option(first_page.locator('#control-style'), 'dial')
        first_page.screenshot(path=str(ROOT/f'test-results/control-first-run-{width}.png'))
        first_page.get_by_role('button', name='Use this style', exact=True).click()
        expect(first_page.locator('.settings')).to_be_hidden()
        expect(first_page.locator('#rate-dial')).to_be_visible()
        expect(first_page.locator('#quick-key-shift')).to_be_hidden()
        first_page.reload()
        expect(first_page.locator('.settings')).to_be_hidden()
        expect(first_page.locator('#quick-key-shift')).to_be_hidden()
        first_page.locator('.settings-button').click()
        first_page.locator('.appearance-settings summary').click()
        expect(first_page.locator('#control-style')).to_have_value('dial')
        first_page.locator('#show-key').check()
        expect(first_page.locator('#quick-key-shift')).to_be_visible()
        choose_option(first_page.locator('#control-style'), 'slider')
        expect(first_page.locator('#rate-slider')).to_be_visible()
        first_context.close()
    context = browser.new_context(viewport={'width': 1440, 'height': 900})
    context.route('https://soundcloud.com/**', lambda route: route.fulfill(path=str(ROOT/'tests/fixtures/inline-fixture.html'), content_type='text/html'))
    context.add_init_script(userscript_source())
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto('https://soundcloud.com/test-artist/first-track')
    quick_key = page.locator('#quick-key-shift')
    expect(quick_key).to_be_visible()
    expect(quick_key).to_have_value('0')
    choose_option(quick_key, '3')
    expect(page.locator('#key-shift')).to_have_value('3')
    assert page.evaluate("localStorage.getItem('soundcloud.tempo.keyShift')") == '3'
    quick_key.press('ArrowDown')
    expect(quick_key).to_have_value('2.5')
    choose_option(quick_key, '0')
    page.locator('.settings-button').click()
    page.locator('.appearance-settings summary').click()
    style = page.locator('#control-style')
    choose_option(style, 'dial')
    page.locator('#apply-saved').press('Escape')
    dial = page.locator('#rate-dial')
    expect(dial).to_be_visible()
    expect(page.locator('#rate-slider')).to_be_hidden()
    dial.press('Home')
    expect(page.locator('#rate-number')).to_have_value('0.25')
    dial.press('ArrowUp')
    expect(page.locator('#rate-number')).to_have_value('0.275')
    dial.press('End')
    expect(page.locator('#rate-number')).to_have_value('4')
    dial.dblclick()
    expect(page.locator('#rate-number')).to_have_value('1')
    assert dial.evaluate('el=>el.style.getPropertyValue("--dial-angle")') == '0deg'
    box = dial.bounding_box()
    page.mouse.move(box['x']+15, box['y']+15)
    page.mouse.down()
    page.mouse.move(box['x']+15, box['y']-145)
    page.mouse.up()
    expect(page.locator('#rate-number')).to_have_value('2')
    page.mouse.move(box['x']+15, box['y']+15)
    page.mouse.down()
    page.keyboard.down('Shift')
    page.mouse.move(box['x']+15, box['y']-145)
    page.keyboard.up('Shift')
    page.mouse.up()
    expect(page.locator('#rate-number')).to_have_value('2.297')
    dial.press('End')
    page.mouse.move(box['x']+15, box['y']+15)
    page.mouse.down()
    page.mouse.move(box['x']+15, box['y']-145)
    page.mouse.move(box['x']+15, box['y']+15)
    page.mouse.up()
    expect(page.locator('#rate-number')).to_have_value('2')
    page.locator('#rate-number').fill('1.25')
    page.locator('#rate-number').press('Tab')
    expect(page.locator('#rate-number')).to_have_value('1.25')
    page.screenshot(path=str(ROOT/'test-results/control-dial-desktop.png'))
    page.locator('.settings-button').click()
    page.locator('.advanced-audio > summary').click()
    page.locator('#key-shift').fill('12')
    page.locator('#key-shift').press('Tab')
    expect(quick_key).to_have_value('12')
    expect(dial).to_have_attribute('aria-valuetext', '1.25× · natural pitch +15.86 st')
    page.locator('#preserve-key').check()
    expect(dial).to_have_attribute('aria-valuetext', '1.25× · Preserve key · key shift +12 st')
    choose_option(style, 'vertical')
    page.locator('#apply-saved').press('Escape')
    slider = page.locator('#rate-slider')
    expect(slider).to_have_attribute('aria-orientation', 'vertical')
    expect(slider).to_be_hidden()
    page.locator('#vertical-toggle').click()
    expect(slider).to_be_focused()
    slider.press('End')
    expect(page.locator('#rate-number')).to_have_value('4')
    assert slider.bounding_box()['height'] >= 80
    slider.press('Home')
    expect(page.locator('#rate-number')).to_have_value('0.25')
    slider.press('ArrowUp')
    expect(page.locator('#rate-number')).to_have_value('0.275')
    page.locator('.fader-reset').click()
    expect(page.locator('#rate-number')).to_have_value('1')
    expect(page.locator('.fader-value')).to_have_text('1.00×')
    page.screenshot(path=str(ROOT/'test-results/control-vertical-desktop.png'))
    slider.press('Escape')
    expect(slider).to_be_hidden()
    expect(page.locator('#vertical-toggle')).to_be_focused()
    page.reload()
    expect(quick_key).to_have_value('12')
    expect(slider).to_have_attribute('aria-orientation', 'vertical')
    page.locator('.settings-button').click()
    page.locator('.appearance-settings summary').click()
    page.locator('input[name=appearance][value=oled]').check()
    page.locator('#apply-saved').press('Escape')
    drift = {'before': page.locator('body').evaluate('el => getComputedStyle(el).backgroundPosition')}
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationDuration') == '7.5s'
    page.wait_for_timeout(1500)
    drift['after'] = page.locator('body').evaluate('el => getComputedStyle(el).backgroundPosition')
    assert drift['before'] != drift['after'], drift
    page.emulate_media(reduced_motion='reduce')
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationName') == 'none'
    page.locator('.settings-button').click()
    page.locator('#star-motion').check()
    page.locator('#star-speed').fill('4')
    page.locator('#apply-saved').press('Escape')
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationName') == 'tempo-star-drift'
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationDuration') == '3.75s'
    actual_before = page.locator('body').evaluate('el => getComputedStyle(el).backgroundPosition')
    page.wait_for_timeout(1500)
    actual_after = page.locator('body').evaluate('el => getComputedStyle(el).backgroundPosition')
    assert actual_before != actual_after, (actual_before, actual_after)
    page.reload()
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationName') == 'tempo-star-drift'
    page.locator('.settings-button').click()
    page.locator('.appearance-settings summary').click()
    expect(page.locator('#star-motion')).to_be_checked()
    expect(page.locator('#star-speed')).to_have_value('4')
    page.locator('#star-motion').uncheck()
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationName') == 'none'
    expect(page.locator('#star-speed')).to_be_disabled()
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationName') == 'none'
    page.locator('#apply-saved').press('Escape')
    page.emulate_media(reduced_motion='no-preference')
    assert page.locator('body').evaluate('el => getComputedStyle(el).animationName') == 'none'
    page.set_viewport_size({'width': 390, 'height': 844})
    page.locator('.settings-button').click()
    page.screenshot(path=str(ROOT/'test-results/control-settings-mobile.png'))
    page.locator('#apply-saved').press('Escape')
    page.evaluate("()=>{window.audio=new Audio();audio.muted=true;Object.defineProperty(audio,'duration',{value:200});document.body.append(audio);}")
    page.locator('.settings-button').click()
    page.locator('.open-editor').click()
    minimum, maximum = page.locator('.speed-min'), page.locator('.speed-max')
    minimum.fill('0.5'); minimum.press('Tab')
    maximum.fill('1.5'); maximum.press('Tab')
    expect(page.locator('.speed-range')).to_have_value('custom')
    labels = page.locator('.editor-graph text').all_text_contents()
    assert '0.5×' in labels and '1.5×' in labels, labels
    page.locator('.point-rate').fill('3'); page.locator('.point-rate').press('Tab')
    expect(minimum).to_have_value('0.5')
    expect(maximum).to_have_value('1.5')
    for value in ['', '0.1', '1.5', '5']:
        minimum.fill(value); minimum.press('Tab')
        expect(minimum).to_have_attribute('aria-invalid', 'true')
        expect(page.locator('.speed-range')).to_have_value('custom')
        expect(page.locator('.editor-status')).to_contain_text('minimum below the maximum')
    minimum.fill('0.837'); minimum.press('Tab')
    maximum.fill('0.838'); maximum.press('Tab')
    assert page.locator('.editor-graph .grid').count() <= 20
    assert '0.837×' in page.locator('.editor-graph text').all_text_contents()
    maximum.fill('1.5'); maximum.press('Tab')
    minimum.fill('0.5'); minimum.press('Tab')
    page.locator('.editor-key-shift').fill('-3'); page.locator('.editor-key-shift').press('Tab')
    page.locator('.editor-apply-once').click()
    expect(quick_key).to_have_value('-3')
    page.locator('.editor-close').click()
    choose_option(quick_key, '2')
    page.locator('.settings-button').click(); page.locator('.open-editor').click()
    expect(page.locator('.editor-key-shift')).to_have_value('2')
    expect(minimum).to_have_value('0.5')
    expect(maximum).to_have_value('1.5')
    page.locator('.editor-save').click()
    expect(quick_key).to_have_value('2')
    page.locator('.zoom-fit').click()
    expect(page.locator('.speed-range')).to_have_value('custom')
    expect(minimum).to_have_value('0.75')
    expect(maximum).to_have_value('3')
    # Narrow and desktop captures include the graph bounds and adjacent key picker.
    for width in [1440, 390]:
        page.set_viewport_size({'width': width, 'height': 900})
        maximum.fill('1.5'); maximum.press('Tab')
        minimum.fill('0.5'); minimum.press('Tab')
        page.locator('.point-rate').fill('1'); page.locator('.point-rate').press('Tab')
        panel = page.locator('.tempo-editor')
        panel.evaluate('el=>el.scrollTop=0')
        assert panel.evaluate('el=>el.scrollWidth<=el.clientWidth+1')
        labels = page.locator('.editor-graph text').evaluate_all('''items => items
          .filter(item=>item.textContent.endsWith('×'))
          .map(item=>({top:item.getBoundingClientRect().top,bottom:item.getBoundingClientRect().bottom}))
          .sort((a,b)=>a.top-b.top)''')
        assert all(a['bottom'] <= b['top'] for a,b in zip(labels, labels[1:])), labels
        page.screenshot(path=str(ROOT/f'.impeccable/review/editor-range-{width}.png'))
    page.locator('.editor-close').click()
    for width in [1497, 1050, 900, 768, 390, 320]:
        page.set_viewport_size({'width': width, 'height': 900})
        for control in ['slider', 'dial', 'vertical']:
            page.locator('.settings-button').click()
            if not page.locator('.appearance-settings').evaluate('el=>el.open'):
                page.locator('.appearance-settings summary').click()
            choose_option(style, control)
            page.locator('#apply-saved').press('Escape')
            expect(quick_key).to_be_visible()
            quick_box = quick_key.bounding_box()
            number_box = page.locator('#rate-number').bounding_box()
            assert abs(quick_box['y'] + quick_box['height']/2 - number_box['y'] - number_box['height']/2) <= .5, (width, control, quick_box, number_box)
            rail_box = page.locator({'dial':'#rate-dial', 'vertical':'#vertical-toggle', 'slider':'#rate-slider'}[control]).bounding_box()
            footer = page.locator('.playControls').bounding_box()
            assert rail_box['y'] >= footer['y'] and rail_box['y'] + rail_box['height'] <= footer['y'] + footer['height'], (width, control, rail_box, footer)
            assert rail_box['x'] + rail_box['width'] < quick_box['x'], (width, control)
            group_box = page.locator('.quick-key').bounding_box()
            assert 16 <= group_box['x'] - rail_box['x'] - rail_box['width'] <= 24, (width, control, group_box, rail_box)
            for button in ['prev', 'play', 'next', 'shuffle', 'repeat']:
                box = page.locator('.playControls__' + button).bounding_box()
                assert rail_box['x'] + rail_box['width'] <= box['x'] or box['x'] + box['width'] <= rail_box['x'] or rail_box['y'] + rail_box['height'] <= box['y'] or box['y'] + box['height'] <= rail_box['y'], (width, control, button)
            assert page.locator('.playControls__elements').evaluate('el=>el.scrollWidth<=el.clientWidth+1'), (width, control)
            page.screenshot(path=str(ROOT/f'.impeccable/review/key-{control}-{width}.png'))
            if width == 1497:
                page.locator('#other-input').click()
                page.locator('#soundcloud-tempo-control').screenshot(path=str(ROOT/f'.impeccable/review/compact-{control}.png'))
            if control == 'vertical':
                page.locator('#vertical-toggle').click()
                expect(slider).to_be_focused()
                panel_box = page.locator('#tempo-fader').bounding_box()
                fader_box = slider.bounding_box()
                assert abs(fader_box['x'] + fader_box['width']/2 - panel_box['x'] - panel_box['width']/2) <= .5, (width, panel_box, fader_box)
                assert panel_box['y'] >= 0 and panel_box['x'] >= 0 and panel_box['x'] + panel_box['width'] <= width, (width, panel_box)
                assert panel_box['y'] + panel_box['height'] < footer['y'], (width, panel_box, footer)
                assert slider.evaluate('el=>getComputedStyle(el).getPropertyValue("--range-thumb-opacity").trim()') == '1'
                page.screenshot(path=str(ROOT/f'.impeccable/review/key-vertical-open-{width}.png'))
                page.locator('#other-input').click()
                expect(slider).to_be_hidden()
    choose_option(quick_key, '5')
    page.locator('.settings-button').click()
    if not page.locator('.appearance-settings').evaluate('el=>el.open'):
        page.locator('.appearance-settings summary').click()
    page.locator('#show-key').uncheck()
    expect(quick_key).to_be_hidden()
    expect(page.locator('#key-shift')).to_have_value('5')
    assert page.evaluate("localStorage.getItem('soundcloud.tempo.showKey')") == 'false'
    page.locator('#apply-saved').press('Escape')
    page.reload()
    expect(quick_key).to_be_hidden()
    # Reload reapplies the saved timeline's +2 shift; the default stays +5.
    expect(page.locator('#key-shift')).to_have_value('2')
    assert page.evaluate("localStorage.getItem('soundcloud.tempo.keyShift')") == '5'
    for width in [1440, 390, 320]:
        page.set_viewport_size({'width': width, 'height': 900})
        for control in ['slider', 'dial', 'vertical']:
            page.locator('.settings-button').click()
            if not page.locator('.appearance-settings').evaluate('el=>el.open'):
                page.locator('.appearance-settings summary').click()
            choose_option(style, control)
            page.locator('#apply-saved').press('Escape')
            expect(quick_key).to_be_hidden()
            assert page.locator('.controls').evaluate('el=>el.scrollWidth<=el.clientWidth+1'), (width, control)
            assert page.locator('.playControls__elements').evaluate('el=>el.scrollWidth<=el.clientWidth+1'), (width, control)
            page.screenshot(path=str(ROOT/f'.impeccable/review/hidden-key-{control}-{width}.png'))
    page.evaluate("()=>{localStorage.setItem('soundcloud.tempo.showKey','true');window.dispatchEvent(new StorageEvent('storage',{key:'soundcloud.tempo.showKey'}));}")
    expect(quick_key).to_be_visible()
    expect(quick_key).to_have_value('2')
    expect(page.locator('#show-key')).to_be_checked()
    assert not errors, errors
    browser.close()
    print(json.dumps({'control_styles_and_actual_star_motion':'passed', 'drift':drift}))
