import os
from playwright.sync_api import sync_playwright, expect
from userscript_fixture import ROOT, browser_options, tempo_tick_geometry

BASE = os.environ.get('SITE_URL', 'http://127.0.0.1:4322/')
with sync_playwright() as p:
    browser = p.chromium.launch(**browser_options(), headless=True, args=['--mute-audio'])
    page = browser.new_page(viewport={'width': 1440, 'height': 1100})
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(BASE, wait_until='networkidle')
    page.locator('#preview-fixed').click()
    tempo_tick_geometry(page.locator('.speed-ticks'), page.locator('#demo-speed'), 12)
    page.locator('#preview-timeline').click()
    assert page.locator('audio').evaluate('(audio) => audio.paused && audio.volume === 0.15')
    page.route('**/api/resolve?*', lambda route: route.fulfill(status=502, json={'error': 'Track could not be loaded.'}))
    page.locator('#preview-play').click()
    expect(page.locator('#preview-sample')).to_be_visible()
    page.locator('#preview-sample').click()
    trigger = page.locator('.select-trigger')
    expect(trigger).to_have_accessible_name('Demo pitch mode Natural')
    trigger.click()
    page.get_by_role('option', name='Natural', exact=True).press('ArrowDown')
    page.get_by_role('option', name='Preserve key', exact=True).press('Enter')
    expect(trigger).to_contain_text('Preserve key')
    expect(trigger).to_have_accessible_name('Demo pitch mode Preserve key')
    expect(trigger).to_be_focused()
    trigger.press('ArrowDown')
    page.get_by_role('option', name='Preserve key', exact=True).press('Escape')
    expect(trigger).to_be_focused()
    page.locator('#preview-play').click()
    page.wait_for_function('document.querySelector("audio").currentTime > 0.5')
    page.wait_for_function('document.querySelector("audio").preservesPitch === false', timeout=15000)
    assert 'browser key' not in page.locator('#demo-status').inner_text()
    source = page.locator('audio').get_attribute('src')
    page.evaluate("dispatchEvent(new PageTransitionEvent('pagehide', {persisted: true}))")
    assert page.locator('audio').evaluate('(audio) => audio.paused')
    assert page.locator('audio').get_attribute('src') == source
    page.evaluate("dispatchEvent(new PageTransitionEvent('pageshow', {persisted: true}))")
    page.locator('#preview-play').click()
    page.wait_for_function('!document.querySelector("audio").paused')
    page.locator('#preview-fixed').click()
    page.locator('#demo-speed-number').fill('0.75')
    page.locator('#demo-speed-number').press('Tab')
    assert page.locator('audio').evaluate('(audio) => audio.playbackRate') == .75
    expect(page.locator('#preview-follow')).not_to_be_checked()
    page.locator('#preview-play').click()
    assert page.locator('audio').evaluate('(audio) => audio.paused')
    page.locator('#preview-seek').fill('12')
    page.wait_for_function('Math.abs(document.querySelector("audio").currentTime - 12) < 0.2')
    page.locator('#preview-reset').click()
    assert page.locator('audio').evaluate('(audio) => audio.paused && audio.currentTime < 0.2')
    expect(trigger).to_contain_text('Natural')
    expect(page.locator('#preview-follow')).to_be_checked()
    expect(page.locator('#demo-copy')).to_be_disabled()
    page.locator('#preview-loader summary').click()
    page.route('**/api/resolve?*', lambda route: route.fulfill(status=502, json={'error': 'Track could not be loaded.'}))
    page.locator('#preview-url').fill('https://soundcloud.com/artist/track')
    page.locator('#preview-link-form button').click()
    expect(page.locator('#demo-status')).to_contain_text('could not be loaded')
    page.locator('#preview-file').set_input_files({'name': 'broken.wav', 'mimeType': 'audio/wav', 'buffer': b'not audio'})
    expect(page.locator('#demo-status')).to_contain_text('could not be loaded')
    page.reload(wait_until='networkidle')
    for width in [320, 360, 390, 768, 1440]:
        page.set_viewport_size({'width': width, 'height': 1100})
        page.locator('#preview-loader').evaluate('(el) => el.open = true')
        page.locator('.demo-details').first.evaluate('(el) => el.open = true')
        assert page.evaluate('document.documentElement.scrollWidth <= document.documentElement.clientWidth'), width
        page.locator('#preview-loader').evaluate('(el) => el.open = false')
        page.locator('.demo-details').first.evaluate('(el) => el.open = false')
        for image in page.locator('.capture-surface img').all():
            image.scroll_into_view_if_needed()
            image.evaluate('(image) => image.decode()')
        page.evaluate('scrollTo(0,0)')
        if width in [390, 1440]: page.screenshot(path=str(ROOT/'test-results'/f'release-site-{width}.png'), full_page=True)
    trigger.click()
    page.wait_for_timeout(200)
    page.screenshot(path=str(ROOT/'test-results'/'release-menu.png'))
    page.get_by_role('option', name='Natural', exact=True).press('Escape')
    pending = []
    page.route('**/screenshots/player-controls.png', lambda route: pending.append(route))
    page.reload(wait_until='domcontentloaded')
    page.locator('.capture-player img').scroll_into_view_if_needed()
    expect(page.locator('.capture-player picture')).to_have_attribute('data-loading', '')
    page.wait_for_timeout(100)
    assert pending
    pending[0].fulfill(status=404, body='missing')
    expect(page.locator('.capture-player picture')).to_have_attribute('data-error', '')
    expect(page.locator('.capture-player picture')).not_to_have_attribute('data-loading', '')
    assert errors == [], errors
    browser.close()
print('Live sample, WASM, pitch menu, tempo, seek, reset, file errors, resolver failure, skeleton failure and responsive layouts passed.')
