server {
    listen 80;
    server_name 88.96.45.138;
    server_tokens off;
    location /.well-known/acme-challenge/ {
        root /var/www/tempo-acme;
    }
    location / {
        return 301 https://88.96.45.138$request_uri;
    }
}
