server {
    listen 443 ssl;
    server_name tempo.88-96-45-138.sslip.io;
    server_tokens off;
    ssl_certificate /etc/letsencrypt/live/tempo.88-96-45-138.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tempo.88-96-45-138.sslip.io/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 1k;
    access_log off;
    include /etc/nginx/tempo-routes.conf;
}
